apiVersion: apps/v1
kind: Deployment
metadata:
  #namespace: frontend
  name: cartservice-dep
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
      - name: cartservice-con
        image: mcr.microsoft.com/dotnet/sdk:5.0.201 #images qui se trouvent 
        ports:
        - containerPort: 7070
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 100m
        env:
        - name: PORT
          value: "7070"
        - name: REDIS_ADDR
          value: "35.203.74.35:6379"
---
apiVersion: v1
kind: Service
metadata:
  #namespace: redis
  name: cartservice-svc
spec:
  selector:
    app: cartservice
  ports:
  - port: 7070
    targetPort: 7070
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cartservice-dep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cartservice-dep
  minReplicas : 1
  maxReplicas : 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
