---
steps:
  # Build the container image
- name: 'gcr.io/cloud-builders/docker'
  id: build
  args: ['build', '-t', 'gcr.io/formationgcp-baptiste/pfr/cartservice:latest', '.']
#Deploy de notre image
- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args: ['apply', '-f', './manifest/4-cartservice.yml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=northamerica-northeast1-a'
  - 'CLOUDSDK_COMPUTE_REGION=northamerica-northeast1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-pfr-main'
  #step 3
- name: 'gcr.io/cloud-builders/kubectl'
  id: Update-manifest
  args: [
   'set', 
   'image', 
   'deployment', 
   'cartservice-dep', 
   'cartservice-con=gcr.io/formationgcp-baptiste/pfr/cartservice:latest'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=northamerica-northeast1-a'
  - 'CLOUDSDK_COMPUTE_REGION=northamerica-northeast1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-pfr-main'
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args: ['push', 'gcr.io/formationgcp-baptiste/pfr/cartservice:latest']
